### PR TITLE
Removed defaults from .cpp

### PR DESCRIPTION
**Pull request by mcsarge**
This library does not work with the compiler - you must not define the default values in both the .h and the .cpp. I have removed them from the .cpp only. no other changes.

### CODE REVIEW

**Comment by kpochwala** [comment]
Did the same, I did not see that there is already PR: https://github.com/ArduinoGetStarted/led/pull/3 so closed mine.

**Comment by ArduinoGetStarted** [comment]
Dear @mcsarge and @kpochwala ,

Thank you for your comments.

Regarding your requests, which compilers did you use?
I compiled via Arduino IDE !.8.x and it works well without removing the default values.

**Comment by hoc-ht** [comment]
@ArduinoGetStarted I got same issue.
I'm using Arduino IDE 2.1.0.

**Comment by hoc-ht** [comment]
@ArduinoGetStarted Please read this thread: [https://forum.arduino.cc/t/default-arguments/40909/5](https://forum.arduino.cc/t/default-arguments/40909/5)

**Review by hoc-ht — APPROVED** [review]

**Comment by kpochwala** [comment]
@ArduinoGetStarted I am using platformio with ESP32-S3 toolchain based on GCC 8.4.0: `toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5`

**Comment by ArduinoGetStarted** [comment]
The library has been updated.

**Pull request closed without merging**
